// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalR.Infrastructure;

namespace SignalR.Infrastructure.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    [Migration("20200224210230_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SignalR.Contracts.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac6d6c33-6bbf-4446-888d-3292e5c181ea"),
                            CreatedBy = "System",
                            CreatedDateUtc = new DateTime(2020, 2, 24, 21, 2, 29, 963, DateTimeKind.Utc).AddTicks(188),
                            Email = "demo@demo.com",
                            IsDeleted = false,
                            LastModifiedBy = "System",
                            LastModifiedDateUtc = new DateTime(2020, 2, 24, 21, 2, 29, 963, DateTimeKind.Utc).AddTicks(188),
                            TenantGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
