// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalR.Infrastructure;

namespace SignalR.Infrastructure.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    partial class SQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SignalR.Contracts.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06bfc2e0-a474-471f-8a0a-28cc2e3e5bb1"),
                            ConnectionId = "12345",
                            CreatedBy = "System",
                            CreatedDateUtc = new DateTime(2020, 2, 24, 22, 5, 13, 50, DateTimeKind.Utc).AddTicks(2085),
                            Email = "demo@demo.com",
                            IsDeleted = false,
                            LastModifiedBy = "System",
                            LastModifiedDateUtc = new DateTime(2020, 2, 24, 22, 5, 13, 50, DateTimeKind.Utc).AddTicks(2085),
                            TenantGuid = new Guid("a8aeb35c-02cf-4626-9062-934eb2ac3580"),
                            TenantType = "Carrier"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
