// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalR.Infrastructure;

namespace SignalR.Infrastructure.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    partial class SQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SignalR.Contracts.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModifiedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("160071b0-a6f3-4832-a734-40d0e773f127"),
                            ConnectionId = "12345",
                            CreatedDateUtc = new DateTime(2020, 2, 25, 21, 21, 26, 946, DateTimeKind.Utc).AddTicks(1669),
                            Email = "demo@demo.com",
                            IsDeleted = false,
                            LastModifiedDateUtc = new DateTime(2020, 2, 25, 21, 21, 26, 946, DateTimeKind.Utc).AddTicks(1669),
                            TenantGuid = new Guid("3bf1ef56-84f5-434b-aaaf-e0a5040f87bd"),
                            TenantType = "Carrier"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
